# coding: utf-8

"""
    Eliona API

    API to access Eliona Smart Building Assistant  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Generated by: https://openapi-generator.tech
"""

from eliona.api_client.paths.agent_devices_agent_class_agent_device_id_mappings.get import GetAgentDeviceMappingsById
from eliona.api_client.paths.agents_agent_class_agent_id_devices.get import GetAgentDevicesById
from eliona.api_client.paths.agents.get import GetAgents
from eliona.api_client.paths.agents_agent_class.get import GetAgentsByClass
from eliona.api_client.paths.agents_agent_class.put import PutAgentByClass
from eliona.api_client.paths.agents_agent_class_agent_id_devices.put import PutAgentDeviceById
from eliona.api_client.paths.agent_devices_agent_class_agent_device_id_mappings.put import PutAgentDeviceMappingById


class AgentsApi(
    GetAgentDeviceMappingsById,
    GetAgentDevicesById,
    GetAgents,
    GetAgentsByClass,
    PutAgentByClass,
    PutAgentDeviceById,
    PutAgentDeviceMappingById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
