# coding: utf-8

"""
    Eliona API

    API to access Eliona Smart Building Assistant  # noqa: E501

    The version of the OpenAPI document: 2.4.3
    Generated by: https://openapi-generator.tech
"""

from eliona.api_client.paths.alarms_alarm_rule_id.get import GetAlarmById
from eliona.api_client.paths.alarms_history_alarm_rule_id.get import GetAlarmHistoryById
from eliona.api_client.paths.alarms.get import GetAlarms
from eliona.api_client.paths.alarms_history.get import GetAlarmsHistory
from eliona.api_client.paths.alarms_highest.get import GetHighestAlarms
from eliona.api_client.paths.alarms_alarm_rule_id.patch import PatchAlarmById


class AlarmsApi(
    GetAlarmById,
    GetAlarmHistoryById,
    GetAlarms,
    GetAlarmsHistory,
    GetHighestAlarms,
    PatchAlarmById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
