# coding: utf-8

"""
    Eliona API

    API to access Eliona Smart Building Assistant  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Generated by: https://openapi-generator.tech
"""

from eliona.api_client.paths.alarm_rules_alarm_rule_id.get import GetAlarmRuleById
from eliona.api_client.paths.alarm_rules.get import GetAlarmRules
from eliona.api_client.paths.alarm_rules.put import PutAlarmRule


class AlarmRulesApi(
    GetAlarmRuleById,
    GetAlarmRules,
    PutAlarmRule,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
